### ISSUE TITLE
UI Suggestion

### ISSUE THREAD

**Issue by omayhemo** [anhaehne/hhnl.HomeAssistantNet#17]
I know I'm all up in your face...  I hope you find it helpful rather than bothersome, because I LOVE your work here.  

It would be great to some how segregate the automation list by class name.
For example from my image, I'd have a single link for the BathFans where by all the methods decorated with Automation within the BathFans.cs would only be listed.  And another link for HomeMode, where all those automations are listed.

Thoughts?

![image](https://user-images.githubusercontent.com/2934415/125099396-94733e80-e09d-11eb-87af-19baad25cf50.png)

**Comment by anhaehne** [comment]
Yeah i was thinking something like this as well. Maybe group them by class an make them expand to a list of all automations of that class when clicked. 

Example: https://getbootstrap.com/docs/5.0/components/accordion/#example

Keep the feedback coming. I love hearing about your usecases.

**Comment by omayhemo** [comment]
Yessir, that's what I'm thinking.

**Comment by omayhemo** [comment]
Love the new UI
