### ISSUE TITLE
Expose new entity

### ISSUE THREAD

**Issue by LussyFairMorngTsarbootsektor** [anhaehne/hhnl.HomeAssistantNet#25]
I am currently converting from NodeRED to HomeAssistantNet. 

In my NodeRED flow I take a "raw" value from a sensor, perform some arithmetic and expose the new value as a new entity using the "Entity Node"

Is there any way to expose a new entity to HA using HomeAssistantNet like that ? I couldn't find it explicitly mentioned either in the documentation or the [project](https://github.com/anhaehne/hhnl.HomeAssistantNet/projects/1)

**Comment by anhaehne** [comment]
Right now there is no way to create new entities. The easiest way currently to expose values to Homeassistent is to define input entities an set their value. 

I will certainly look into defining new entities in the future.

**Comment by anhaehne** [comment]
I've created a new To Do so i will close this issue.
