### ISSUE TITLE
Not reconnecting to Home Assistant after losing connection

### ISSUE THREAD

**Issue by MaxG88** [anhaehne/hhnl.HomeAssistantNet#26]
### Issue
When I restart Home Assistant, C# for Home Assistant does not automatically reconnect. I need to restart the container to have it reconnect. It also seems to happen at random after a few days.

### Environment
C# for Home Assistant in Docker, built from the latest dev image with the connection reliability fix
Home Assistant in LXC, reachable from C# for Home Assistant

### How to reproduce
1. Restart Home Assistant
2. (Try to) Trigger a C# for Home Assistant automation

### Expected behaviour
C# for Home Assistant should keep trying to reconnect to Home Assistant after losing connection.

**Comment by anhaehne** [comment]
Can you show me the log files?

**Comment by MaxG88** [comment]
Unfortunately, the logs don't show anything after restarting Home Assistant.
Here are the kind of logs I would get before restarting Home Assistant, when my automations trigger:
```
dbug: hhnl.HomeAssistantNet.Automations.Automation.AutomationService[0]
      Creating snapshot of entities HomeAssistant.Switches+Tp04NightMode.
dbug: hhnl.HomeAssistantNet.Automations.Automation.AutomationService[0]
      Enqueueing automation run 'CS4HA.FanAutomations.KeepNightModeOnTurnOn'. Reason: 'EntityChanged'
dbug: hhnl.HomeAssistantNet.Automations.Automation.Runner.AutomationRunner[0]
      Starting automation run '4ab31f80-4243-4dba-be0c-677be60030b5' at: 08/10/2021 18:33:16 +00:00 Reasons: 'EntityChanged' ChangedEntity: 'fan.tp_04'
dbug: hhnl.HomeAssistantNet.Automations.Automation.AutomationService[0]
      Creating snapshot of entities HomeAssistant.Switches+Tp04NightMode.
dbug: hhnl.HomeAssistantNet.Automations.Automation.AutomationService[0]
      Enqueueing automation run 'CS4HA.FanAutomations.KeepNightModeOnTurnOn'. Reason: 'EntityChanged'
dbug: hhnl.HomeAssistantNet.Automations.Automation.Runner.AutomationRunner[0]
      Starting automation run 'a10f2425-d4fe-4a58-860c-707c30687cc2' at: 08/10/2021 18:33:27 +00:00 Reasons: 'EntityChanged' ChangedEntity: 'fan.tp_04'
```

When clicking `Build & Deploy`, it does seem to reconnect since the automations start triggering again.

**Comment by anhaehne** [comment]
Is this the logging from the addon UI? Please look into supervisor -> c# -> log. Here you will find logging of the whole application, not only of your current automation run.

**Comment by MaxG88** [comment]
I don't run the Home Assistant Supervisor, I built the C# for Home Assistant image manually and run it on a separate Docker instance, and Home Assistant is in a venv on a separate VM, so I unfortunately cannot get you those logs. Do you know of a way to get them outside of Home Assistant?

**Comment by MaxG88** [comment]
Unless you mean the entire application logs from the very start? I can get you those, but there are only logs before it loses connection. Once the connection is lost, no more automations are triggered and nothing is logged. As far as the Docker logs are concerned, anyway.

**Comment by MaxG88** [comment]
Here are the logs: [container.log](https://github.com/anhaehne/hhnl.HomeAssistantNet/files/6971219/container.log)
Nothing new is logged after Home Assistant is restarted.

**Comment by anhaehne** [comment]
Then please enable the file logging as described above.

**Comment by MaxG88** [comment]
[20210811.log](https://github.com/anhaehne/hhnl.HomeAssistantNet/files/6971483/20210811.log)

I started the app, ran a few automations (they worked), restarted Home Assistant at `21:19:00` (converted from my local time to UTC, like in the log file) and tried to trigger automations the same way I did before restarting Home Assistant. They did not trigger.

**Comment by anhaehne** [comment]
Which project did you add the logging to? The `hhnl.HomeAssistantNet.CSharpForHomeAssistant` or the `CS4HA` project?
If you added it to the first, please also add it to the second. 

Improving the reliability of the deployment of the automation application is on my. list.

Please also try to run the automation application (`CS4HA.csproj`) on your pc and then restart home assistant.

**Comment by MaxG88** [comment]
The only project in the solution is CS4HA. That's where I added it.
![image](https://user-images.githubusercontent.com/14253281/129254507-3bf23ee6-086d-4b39-89f5-76e401a8bc61.png)


I tried running on my PC. I also changed the LogLevel to Debug
[20210812-test.log](https://github.com/anhaehne/hhnl.HomeAssistantNet/files/6977906/20210812-test.log)
I don't see anything new unfortunately.

**Comment by anhaehne** [comment]
Can you show me your project? You can send it to `andre-github-inbox [at] outlook.com`.

**Comment by MaxG88** [comment]
Sorry for the late response. Good catch for the nuget packages. I will update them and give you an update on if that worked tomorrow. If it doesn't, I'll send you the project by email.

Thanks.

**Comment by MaxG88** [comment]
The latest prerelease version fixes the issue and automatically reconnects!
I thought just upgrading to the newest Docker image would be enough but now I know I also need to upgrade Nuget packages.

Thank you very much!

**Comment by anhaehne** [comment]
Yeah that is not entirely clear when you start out. I plan on notifying about new nugget versions in the frontend in an upcoming update.

Glad to hear it works now.
