### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by workpioupiou** [anhaehne/hhnl.HomeAssistantNet#34]
Hello, 

I tried to install your addon but I can't, I have the following error :

The command '/bin/sh -c dotnet restore "hhnl.HomeAssistantNet.CSharpForHomeAssistant/hhnl.HomeAssistantNet.CSharpForHomeAssistant.csproj"' returned a non-zero code: 134

Do you now how to correcting it ? 

Thanks !

**Comment by workpioupiou** [comment]
I reopen this issues. I uninstall the addon (because it was stopping just after being start without logs) and now I can't any more install it. I tried to remove the repo bnut nothing change. always the same errors

**Comment by anhaehne** [comment]
Please check you supervisor logs. If you have trouble installing a addon, supervisor should log an error.

**Comment by workpioupiou** [comment]
the end of the logs is :
Step 16/31 : COPY ["src/hhnl.HomeAssistantNet/hhnl.HomeAssistantNet.CSharpForHomeAssistant/hhnl.HomeAssistantNet.CSharpForHomeAssistant.csproj", "hhnl.HomeAssistantNet.CSharpForHomeAssistant/"]
 ---> Using cache
 ---> db2ae988f7ba
Step 17/31 : RUN dotnet restore "hhnl.HomeAssistantNet.CSharpForHomeAssistant/hhnl.HomeAssistantNet.CSharpForHomeAssistant.csproj"
 ---> Using cache
 ---> 25893d37c0e0
Step 18/31 : COPY src/hhnl.HomeAssistantNet .
 ---> Using cache
 ---> 1e8c072cc3e6
Step 19/31 : WORKDIR "/src/hhnl.HomeAssistantNet.CSharpForHomeAssistant"
 ---> Using cache
 ---> 7f01c9d0a367
Step 20/31 : RUN dotnet build "hhnl.HomeAssistantNet.CSharpForHomeAssistant.csproj" -o /app/build
 ---> Running in 7baeed71d0d3
dotnet: error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: unexpected reloc type 0x10

Removing intermediate container 7baeed71d0d3

I didn't remove library or anything :/

**Comment by anhaehne** [comment]
What hardware are you running? 

If you want you can try installing the dev channel. There the add on is prebuild and ha just has to download the docker image. 
Just add `https://github.com/hhnl-HomeAssistantNet/hhnl.HomeAssistantNet-dev` as a repository.

**Comment by workpioupiou** [comment]
I'm on a raspberry pi with home assistant OS

**Comment by anhaehne** [comment]
What version of the raspberry pi?

**Comment by workpioupiou** [comment]
Raspberry pi 4 with 8G ram
