### ISSUE TITLE
Q: How do I create entities?

### ISSUE THREAD

**Issue by doug62** [anhaehne/hhnl.HomeAssistantNet#39]
First off - wow and thanks!

Aside from your documented features, I wish to create virtual devices, I have Inovelli Red Dimmers and want to automate/animate the indicators, would like to expose those as a device so I could control them from dashboard/automations/ etc..

Guessing this doesn't use MQTT but the API but once again - thanks!

**Comment by anhaehne** [comment]
Closing this issue. I have updated the wiki to let new people now that this is currently not supported and a Todo item already exists.
