### ISSUE TITLE
A bit lost...

### ISSUE THREAD

**Issue by doug62** [anhaehne/hhnl.HomeAssistantNet#41]
Hi - Based on the description, I assume that this will somehow create a .cs file with classes that represent devices, or a dll with virtual/partials - how do I trigger that process?  An example or more documentation would be very nice but I love that this project exists - shows great promise.

**Comment by anhaehne** [comment]
Please see the wiki on how to set up you development environment: https://github.com/anhaehne/hhnl.HomeAssistantNet/wiki

**Comment by doug62** [comment]
Thanks - I have followed those steps, after I run build I would expect some sort of generated artifact be it .cs or .dll to be created for my devices - in the wiki link it looks like Lights.* contains a list of devices in your intelligence - mine shows none.

**Comment by anhaehne** [comment]
Have you build your solution? Are there any build errors?

**Comment by anhaehne** [comment]
Sometimes you also have to restart VS to see the generated classes in intellisense.

**Comment by doug62** [comment]
Builds just fine, I noticed your repo utilizes code generation - where and how is that code generated? I would assume some sort of .dll or .cs with partials - so that I could then compile/extend/use them - how is the code/class generated?  Is there a build step in the cs4ha project/solution that I'm not seeing?  Does that happen in your blazor/web/gui   when you hit 'Build & deploy'? Tried building from core cli and VS 2021

**Comment by anhaehne** [comment]
The project utilizes .net source generators. The package hhnl.HomeAssistantNet.Generator has one that generates all the entities. By default it won't generate any files or dlls, those are all in the background.

You can add this to your csproj file : 
``` xml
<PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup>
```
and after you rebuild your project the generated file should be under 
`obj\Debug\net6.0\generated\hhnl.HomeAssistantNet.Generator\hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator`

**Comment by anhaehne** [comment]
I will close this issue for now. Please reopen if needed.
