### ISSUE TITLE
Wiki Documentation Recommendation

### ISSUE THREAD

**Issue by TATERxxWARDY** [anhaehne/hhnl.HomeAssistantNet#43]
Can you provide system requirements for installation in the Wiki? I'm running low on space and wanted to know this before installing. 

Also, for the uninitiated, it might be helpful to include this [handy tool for generating crons](https://crontab.cronhub.io/) under the [cron scheduling section in triggers](https://github.com/anhaehne/hhnl.HomeAssistantNet/wiki/4.-Triggers#cron-expressions), just a thought and certainly understand if you didn't want to include it in your documentation about this project. I absolutely love the project even though I've yet to use it and as a .NET developer I'm looking forward to testing this out.

Also, I currently run HA in docker (supervised), any plans for dockerizing this in the future?

**Comment by anhaehne** [comment]
If you are running HA with supervisor you can just add this as an add-on. If don't you can just build you own docker image. A dockerfile is included in the repository.

My installation currently has ca. 20mb of local data without logs. That is the source code and the deployed appliation. There is also the size of the docker container but i haven't messured that.

**Comment by anhaehne** [comment]
I've added requirements to the wiki.
