### ISSUE TITLE
Do I need to optimize the functions ? 

### ISSUE THREAD

**Issue by workpioupiou** [anhaehne/hhnl.HomeAssistantNet#44]
Hello,
I run some aitomation for some times and the extension seam to take a lot of ram (74% after two days).
Do you have any ideas how can i correct that?

Thank you!

**Comment by anhaehne** [comment]
Without seeing the source of your automations i can't say what is causing the issue. Normally classes containing automations are removed once the automation has run but you might be using static variable or not disposing IDisposables. 

What is the amount of ram you have? Depending on your system, 74% might not be much. My instance of CS4HA is currently sitting at around 140mb.

**Comment by workpioupiou** [comment]
I'm running HA OS on a raspberry pi 4 (8g ram). 
The code is pretty simple (I added comment to be more clear for the post)

```
[Automation]
public async Task VideosourceMotionAlarmAsync(
	HomeAssistant.BinarySensors.Videosource1MotionAlarm motionAlarm, //Alarm motion provide from a camera
	HomeAssistant.Entities.onvifMainstream camera, //The camera entity to get the unique code for start the recording service 
	HomeAssistant.InputBooleans.TurnOnAlarm stateAlarm, //An input boolean to enable or disabled all function link to the alarm
	HomeAssistant.InputBooleans.IsMotionAlarmActive isMotionAlarmActive) //An input boolean to activate/desactivate this function precisely (their are others method of detection like field detection)
{
	_logger.LogInformation($"VideosourceMotionAlarm State is {motionAlarm.State}");
	if (motionAlarm.State == "on" 
		&& stateAlarm.IsOn
		&& isMotionAlarmActive.IsOn)
		await _cameraService.RecordAndSendTelegramNotificationAsync(camera.UniqueId, _defaultTimeRecording, isMotionAlarmActive.FriendlyName);            
}
```
the _cameraService is a singleton get with dependency inhjection :
`serviceCollection.AddSingleton<ICameraService, CameraService>();`


For that you have all the informations here is the code of the recordAsync Method:

```
public async Task RecordAndSendTelegramNotificationAsync(
            string uniqueId,
            uint duration, 
            string friendlyName)
        {
            _logger.LogInformation("Camera has detected something, recording will start soon...");

            var dateNowStr = DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss");
            string videoName = $"record_{friendlyName.Replace(" ","_")}_{uniqueId}_{dateNowStr}";

            await this.SaveRecordingInHa(videoName, uniqueId, duration); //Call the entity service to record a video

            var fileNameFromExecution = ComputeFullPath(videoName); //Determine the path (depending if it's debug or in deployement 

            WaitingUtilVideoIsFinishedToRecord(fileNameFromExecution); //wait

            await _telegramService.SendNotificationVideoMessage($"{friendlyName} has detect something", fileNameFromExecution, "video capture", 1000);
            
            _logger.LogInformation("Camera has finished");
        }
```


It's far from a good coding but I search actually something funtionnal before refractoring.

**Comment by anhaehne** [comment]
That all looks good to me. Might be something in the other methods though. 

Are you able to reproduce this behaviour locally?

**Comment by workpioupiou** [comment]
No, maybe it's when methods are triggers periodically. 
It already to 40% (I restarted it when I was posting the issue).

**Comment by anhaehne** [comment]
Can you show me your project? You can send it to andre-github-inbox [at] outlook.com.

**Comment by workpioupiou** [comment]
I have one to manage the charging of my phone (to disabled the plug when it reach 90% of battery). I was checking it each minute (I think it's a lot). I change it to just be trigger with the sensor of the battery level. I will restart to see if it was that. 

I initially had opened the issue, to know if you had knowledge of a problems concerning performance. If it's in my code I will search to solve it myself (better for understanding and improving myself and to not making you lost time).    

Thanks for your time, I will send you the project if I'm really block and with no other options left.

**Comment by anhaehne** [comment]
I'm not aware of any issues due to frequently running automations. I have automations running every couply seconds without issues.

**Comment by anhaehne** [comment]
I can't see any obvious memory leaks. You could try changing your services to scoped or transient and see if that changes anything. Otherwise i would need a memory dump to see what objects are piling up.

See: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump

**Comment by anhaehne** [comment]
If fixed an issue where multiple instances of the automation application where run. This caused high cpu load. Please update to the latest version.
