### ISSUE TITLE
Installation failing on Raspberry Pi

### ISSUE THREAD

**Issue by jonathanrelf** [anhaehne/hhnl.HomeAssistantNet#45]
**Host**: Home Assistant OS 7.0 production
**Core**: core-2021.12.2
**Supervisor**: supervisor-2021.12.2 stable
Running on **Raspberry Pi 3**

Trying to follow the installation instructions, the install starts, HA restarts at least twice and yet the Add-On remains with an 'Install' state when I browse to it. 

When I look at the Supervisor logs, I see the following. Not sure if the Docker stuff is related to this add-on but I've included it as its after the C# bits.

Anything obvious I should be trying? Or prerequisites steps that are missing?

```
Microsoft (R) Build Engine version 17.0.0-preview-21501-01+bbcce1dff for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  hhnl.HomeAssistantNet.Shared -> /src/hhnl.HomeAssistantNet.Shared/bin/Debug/netstandard2.0/hhnl.HomeAssistantNet.Shared.dll
/src/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web/Components/SecretsEditor.razor(29,42): warning CS8618: Non-nullable property 'Secrets' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/src/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web.csproj]
/usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): warning NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.Extensions.DependencyInjection.Abstractions [6.0.0-rc.2.21480.5, )" or update the version field in the nuspec. [/src/hhnl.HomeAssistantNet.Shared/hhnl.HomeAssistantNet.Shared.csproj]
  Successfully created package '/src/hhnl.HomeAssistantNet.Shared/bin/Debug/hhnl.HomeAssistantNet.Shared.0.10.0.nupkg'.
  hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web -> /src/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web/bin/Debug/net6.0/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web.dll
  hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web (Blazor output) -> /src/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web/bin/Debug/net6.0/wwwroot
  hhnl.HomeAssistantNet.CSharpForHomeAssistant -> /src/hhnl.HomeAssistantNet.CSharpForHomeAssistant/bin/Debug/net6.0/hhnl.HomeAssistantNet.CSharpForHomeAssistant.dll
/usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(155,5): error MSB6006: "dotnet" exited with code 137. [/src/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web.csproj]
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/usr/share/dotnet/sdk/6.0.100-rc.2.21505.57/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/src/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web/hhnl.HomeAssistantNet.CSharpForHomeAssistant.Web.csproj]
Removing intermediate container c8620ab13c04

21-12-16 19:23:03 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57247' coro=<AddonManager.install() done, defined at /usr/src/supervisor/supervisor/jobs/decorator.py:71> exception=AddonsError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 522, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.9/site-packages/docker/models/images.py", line 285, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c dotnet publish "hhnl.HomeAssistantNet.CSharpForHomeAssistant.csproj" -o /app/publish' returned a non-zero code: 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 181, in install
    await addon.instance.install(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 506, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 542, in _build
    raise DockerError() from err
supervisor.exceptions.DockerError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 108, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 184, in install
    raise AddonsError() from err
supervisor.exceptions.AddonsError
```

**Comment by anhaehne** [comment]
Exit code 137 typically means that your process is getting killed because it is running out of memory. How much ram is available when installing the add-on?

Currently the most resource intensive part is the installation because the add-on get's build. If you run low on memory you would have to wait until i get around distributing a prebuild image.

**Comment by jonathanrelf** [comment]
![image](https://user-images.githubusercontent.com/584662/146465216-4cbdf5e0-d9f4-4620-b083-f582d7952ddb.png)

Thanks for the swift response. And it could easily be running out of RAM. Core & Supervisor are reporting a maximum available of 909Mb which isn't a lot in the grand scheme of things. 

The Raspi 3 only has 1Gb total RAM available. 

If we found a way to compile the DLLs for the Raspi without it being done during installation, could an alternative be to have a form of pre-compiled package install instead?

I guess replacing it out for a Raspi 4 with 8Gb RAM would give me more headroom, but I might not be the only person running Home Assistant on smaller devices?

**Comment by anhaehne** [comment]
Precompiling the docker image could resolve the installation issue but you would still have to compile your automations which also might exaust the ressources of your raspberry pi. 

I have to look into the github actions more to set them up to precompile the docker image.

**Comment by anhaehne** [comment]
I've looked into pre compiling the docker images for the different architectures but it seems like currently armv7 is not supported or has issues. The problem here is that the raspberry pi 3 runs in a pseudo armv7 mode and i don't know if you would be able to install it. 

If you want to try, i can update my dev repository and you could try installing from there.

**Comment by jonathanrelf** [comment]
Does the Raspberry Pi 4 use a different architecture?
Just wondering if the extra RAM and more modern support might be worth investing in even beyond trying to get this to work on a Pi 3.

**Comment by anhaehne** [comment]
The pi 3 is armv8 but apparently at least raspian reports armv7 if not configured otherwise. Can you check in home assistant `Configruation > Settings > Info` what it says under architecture? If it is armv8 you are fine.

I think the most limiting factor on the pi3 will be the RAM. But then again the pi4 with more RAM is really expensive right now.

**Comment by anhaehne** [comment]
I've created prebuild images in my dev repository. Please try adding this repository and install from there: `https://github.com/hhnl-HomeAssistantNet/hhnl.HomeAssistantNet-dev`

**Comment by anhaehne** [comment]
The prebuild images are now also available on the main branch. I will close this issue for now. Please reopen if needed.

**Comment by jonathanrelf** [comment]
Thank you for your work on this and apologies for the sluggish feedback. I can confirm that, from the main repository, this now works just fine on my Raspberry Pi 3 without any extra steps.
