### ISSUE TITLE
Updated to 0.11.3 and fails to start

### ISSUE THREAD

**Issue by ErikSharp** [anhaehne/hhnl.HomeAssistantNet#51]
The release notes state to update to the latest nuget packages. I have done this for my project, but when starting the add-on a HA dialog comes up saying:

Failed to start add-on

Image limeray/c-sharp-for-homeassistant:0.11.3 does not exist for addon_5dc342e7_c_sharp_for_home-assistant

What are the actual steps that should be performed to update?

**Comment by anhaehne** [comment]
What hardware are you using?

**Comment by ErikSharp** [comment]
Raspberry Pi 4

**Comment by anhaehne** [comment]
When you are in the AddOn page does it say: `Current version: 0.11.3` ? 
Can you access the raspberry pi via ssh? If so please try running `docker pull limeray/c-sharp-for-homeassistant:0.11.3`.

**Comment by ErikSharp** [comment]
Yes, the AddOn page shows the current version as 0.11.3

I have connected via ssh and run the command. The AddOn now starts and the automations are functioning. I have not built or deployed any changes on my end and my csproj still shows:

<PackageReference Include="hhnl.HomeAssistantNet.Automations" Version="0.10.0" />
<PackageReference Include="hhnl.HomeAssistantNet.Generator" Version="0.10.1" />
<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.0-rc.2.21480.5" />

So I assume that I am to update these. Is that correct?

**Comment by anhaehne** [comment]
Yes, you have to update the nuget packages in you project.

**Comment by ErikSharp** [comment]
I have added the three nuget packages to update them as follows in the csproj:

PackageReference Include="hhnl.HomeAssistantNet.Automations" Version="0.11.3"
PackageReference Include="hhnl.HomeAssistantNet.Generator" Version="0.11.3"
PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.0"

When trying to compile, I am getting the following compiler exception:

CSC : error HHNL005: An unhandled exception occured 'System.Reflection.TargetInvocationException'. HomeAssistance url: 'http://supervisor/core/' Token: 'f9a5125980...' Message 'Exception has been thrown by the target of an invocation.' InnerException: 'System.MissingMethodException: Method not found: 'Void RestSharp.RestClient.set_AutomaticDecompression(Boolean)'. [/temp/build/CS4HA/CS4HA.csproj]

This is then followed by errors about my sensors:

/temp/build/CS4HA/WoolwichAutomations.cs(73,23): error CS0246: The type or namespace name 'HomeAssistant' could not be found (are you missing a using directive or an assembly reference?) [/temp/build/CS4HA/CS4HA.csproj]

In HA, trying to Build & Deploy is giving the same errors.

To be clear, HA is still running the old version of my code.

**Comment by anhaehne** [comment]
You are correct, there is an error in the creation of the entities. I will have to look into the issue.

**Comment by ErikSharp** [comment]
Not sure if it's relevant, but I saw this double naming in the relative path when browsing to the entity definitions:

/hhnl.HomeAssistantNet.Generator/hhnl.HomeAssistantNet.Generator.SourceGenerator.SourceGenerator/HomeAssistant_Sensors.cs

Is it supposed to say SourceGenerator twice like that?

**Comment by anhaehne** [comment]
I've pushed the nuget package `hhnl.HomeAssistantNet.Generator 0.11.4` which should resolve the issue.

**Comment by ErikSharp** [comment]
Not sure if we're waiting on a NuGet batch process, but 0.11.4 hasn't shown up yet.

**Comment by ErikSharp** [comment]
Sorry, my bad. I was looking at hhnl.HomeAssistantNet.Automations.

**Comment by ErikSharp** [comment]
We are getting a compiler error for the generation of binary sensors:

\\192.168.1.111\config\c-sharp-for-homeassistant\source\CS4HA\WoolwichAutomations.cs(129,27): error CS0234: The type or namespace name 'BinarySensors' does not exist in the namespace 'HomeAssistant' (are you missing an assembly reference?) [\\192.168.1.111\config\c-sharp-for-homeassistant\source\CS4HA\CS4HA.csproj]

**Comment by anhaehne** [comment]
Oh i'm sorry i forgot do document that all sensors are now available in the `Sensors` class. So just replate `BinarySensors` with `Sensors`.

**Comment by ErikSharp** [comment]
OK, everything is looking good. I have noticed another breaking change in that some of my sensor battery entities that were `Sensor` types are now `NumericSensor` types.

Thanks for the hard work and the help today.

**Comment by anhaehne** [comment]
Yes some sensors have metadata indicating the type. When possible o try to use that do create the appropriate type of sensor. That's one of the reasons why binary sensors are now created in the sensors class.
